import React from 'react';

interface MarkdownViewerProps {
  content: string;
  className?: string;
}

/**
 * Safe, beautiful, and reliable WYSIWYG / Markdown Viewer.
 * Supports HTML (from Tiptap/Rich Text Editor) as well as Markdown and plain text with bullet points (-, *, •).
 */
export function MarkdownViewer({ content, className = '' }: MarkdownViewerProps) {
  if (!content) return null;

  const trimmed = content.trim();

  // Detect HTML content (generated by Tiptap or rich text editor)
  const isHtml =
    /^\s*<[a-z][\s\S]*>/i.test(trimmed) ||
    trimmed.includes('<p>') ||
    trimmed.includes('</p>') ||
    trimmed.includes('</div>') ||
    trimmed.includes('</span>') ||
    trimmed.includes('</ul>') ||
    trimmed.includes('</ol>') ||
    trimmed.includes('<li>') ||
    trimmed.includes('<h1') ||
    trimmed.includes('<h2') ||
    trimmed.includes('<h3') ||
    trimmed.includes('<br') ||
    trimmed.includes('<hr');

  if (isHtml) {
    return (
      <div
        className={`prose-editor text-xs leading-relaxed text-inherit ${className}`}
        dangerouslySetInnerHTML={{ __html: content }}
      />
    );
  }

  // Pre-process lines: if a line is an orphan bullet ('•', '-', '*'), join it with the next non-empty line
  const rawLines = content.split('\n');
  const processedLines: string[] = [];

  for (let i = 0; i < rawLines.length; i++) {
    const line = rawLines[i];
    const trimmedLine = line.trim();

    if ((trimmedLine === '•' || trimmedLine === '-' || trimmedLine === '*') && i + 1 < rawLines.length) {
      let nextIdx = i + 1;
      while (nextIdx < rawLines.length && rawLines[nextIdx].trim() === '') {
        nextIdx++;
      }
      if (nextIdx < rawLines.length) {
        processedLines.push(`${trimmedLine} ${rawLines[nextIdx].trim()}`);
        i = nextIdx;
        continue;
      }
    }
    processedLines.push(line);
  }

  const elements: React.ReactNode[] = [];
  let listItems: string[] = [];
  let orderedItems: { num: string; text: string }[] = [];

  function flushList() {
    if (listItems.length > 0) {
      elements.push(
        <ul key={`ul-${elements.length}`} className="list-disc pl-5 space-y-1 my-2">
          {listItems.map((item, idx) => (
            <li key={idx} className="my-0.5">{renderInlineMarkdown(item)}</li>
          ))}
        </ul>
      );
      listItems = [];
    }
    if (orderedItems.length > 0) {
      elements.push(
        <ol key={`ol-${elements.length}`} className="list-decimal pl-5 space-y-1 my-2">
          {orderedItems.map((item, idx) => (
            <li key={idx} className="my-0.5">{renderInlineMarkdown(item.text)}</li>
          ))}
        </ol>
      );
      orderedItems = [];
    }
  }

  let inCodeBlock = false;
  let codeBlockLines: string[] = [];

  processedLines.forEach((line, index) => {
    // Handle Code Block ```
    if (line.trim().startsWith('```')) {
      if (inCodeBlock) {
        elements.push(
          <pre
            key={`code-${elements.length}`}
            className="bg-zinc-950 dark:bg-zinc-900 text-zinc-100 p-3 rounded-xl text-xs font-mono overflow-x-auto my-2 border border-zinc-800"
          >
            <code>{codeBlockLines.join('\n')}</code>
          </pre>
        );
        codeBlockLines = [];
        inCodeBlock = false;
      } else {
        flushList();
        inCodeBlock = true;
      }
      return;
    }

    if (inCodeBlock) {
      codeBlockLines.push(line);
      return;
    }

    // Handle Unordered List (- or * or •)
    const listMatch = line.match(/^[\s]*[-*•]\s*(.*)$/);
    if (listMatch) {
      const itemContent = listMatch[1].trim();
      if (itemContent) {
        if (orderedItems.length > 0) flushList();
        listItems.push(itemContent);
        return;
      }
    }

    // Handle Ordered List (1. or 1))
    const orderedMatch = line.match(/^[\s]*(\d+)[\.\)]\s*(.*)$/);
    if (orderedMatch) {
      const itemContent = orderedMatch[2].trim();
      if (itemContent) {
        if (listItems.length > 0) flushList();
        orderedItems.push({ num: orderedMatch[1], text: itemContent });
        return;
      }
    }

    flushList();

    // Handle Headers #, ##, ###
    if (line.startsWith('# ')) {
      elements.push(
        <h1 key={`h1-${index}`} className="text-base font-extrabold text-inherit my-2">
          {renderInlineMarkdown(line.slice(2))}
        </h1>
      );
      return;
    }
    if (line.startsWith('## ')) {
      elements.push(
        <h2 key={`h2-${index}`} className="text-sm font-bold text-inherit my-2">
          {renderInlineMarkdown(line.slice(3))}
        </h2>
      );
      return;
    }
    if (line.startsWith('### ')) {
      elements.push(
        <h3 key={`h3-${index}`} className="text-xs font-bold text-inherit my-1.5">
          {renderInlineMarkdown(line.slice(4))}
        </h3>
      );
      return;
    }

    // Handle Blockquote >
    if (line.startsWith('> ')) {
      elements.push(
        <blockquote
          key={`quote-${index}`}
          className="border-l-4 border-purple-500 pl-3 italic text-inherit opacity-90 my-2 text-xs"
        >
          {renderInlineMarkdown(line.slice(2))}
        </blockquote>
      );
      return;
    }

    // Handle Horizontal Rule --- or ***
    if (line.trim() === '---' || line.trim() === '***') {
      elements.push(<hr key={`hr-${index}`} className="my-3 border-zinc-200 dark:border-zinc-800 opacity-40" />);
      return;
    }

    // Empty lines
    if (line.trim() === '') {
      elements.push(<div key={`space-${index}`} className="h-1.5" />);
      return;
    }

    // Standard Paragraph
    elements.push(
      <p key={`p-${index}`} className="my-1 text-xs leading-relaxed text-inherit">
        {renderInlineMarkdown(line)}
      </p>
    );
  });

  flushList();

  return <div className={`prose-editor ${className}`}>{elements}</div>;
}

/**
 * Helper to parse inline markdown formatting like **bold**, *italic*, `code`, and [links](url).
 */
function renderInlineMarkdown(text: string): React.ReactNode[] {
  const parts: React.ReactNode[] = [];
  const regex = /(\[.*?\]\(.*?\)|\`.*?\`|\*\*.*?\*\*|\*.*?\*)/g;
  const rawParts = text.split(regex);

  rawParts.forEach((part, idx) => {
    if (!part) return;

    // Link: [Text](URL)
    const linkMatch = part.match(/^\[(.*?)\]\((.*?)\)$/);
    if (linkMatch) {
      parts.push(
        <a
          key={idx}
          href={linkMatch[2]}
          target="_blank"
          rel="noopener noreferrer"
          className="text-purple-600 dark:text-purple-400 font-semibold underline hover:opacity-80"
        >
          {linkMatch[1]}
        </a>
      );
      return;
    }

    // Inline Code: `code`
    if (part.startsWith('`') && part.endsWith('`') && part.length > 2) {
      parts.push(
        <code
          key={idx}
          className="bg-black/10 dark:bg-black/30 text-inherit px-1.5 py-0.5 rounded text-[11px] font-mono border border-zinc-200 dark:border-zinc-700"
        >
          {part.slice(1, -1)}
        </code>
      );
      return;
    }

    // Bold: **text**
    if (part.startsWith('**') && part.endsWith('**') && part.length > 4) {
      parts.push(
        <strong key={idx} className="font-black text-inherit">
          {part.slice(2, -2)}
        </strong>
      );
      return;
    }

    // Italic: *text*
    if (part.startsWith('*') && part.endsWith('*') && part.length > 2) {
      parts.push(
        <em key={idx} className="italic">
          {part.slice(1, -1)}
        </em>
      );
      return;
    }

    // Plain Text
    parts.push(<span key={idx}>{part}</span>);
  });

  return parts;
}
